{{- if .Values.destinationRule.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
{{ include "varnish.labels" . | indent 4 }}
spec:
  host: "{{ template "varnish.fullname" . }}.{{ .Release.Namespace }}.svc.{{ default "cluster.local" .Values.clusterDomain }}"
  trafficPolicy:
    tls:
      mode: "{{ default "DISABLE" .Values.destinationRule.mode }}"
{{- end }}
