name: drupal
apiVersion: v2
type: application
version: 0.15.0
appVersion: 4.2.1
description: Drupal 8/9 variant of the Web Experience Toolkit (WxT).
keywords:
- drupal
- cms
- wxt
- http
- web
- application
- php
home: http://www.drupal.org/project/wxt
icon: https://bitnami.com/assets/stacks/drupal/img/drupal-stack-220x234.png
sources:
- https://github.com/drupalwxt/wxt
maintainers:
- name: sylus
  email: william.hearn@canada.ca
- name: zachomedia
  email: zachary.seguin@canada.ca
engine: gotpl
dependencies:
  - name: mysql
    version: 1.6.2
    repository: https://charts.helm.sh/stable
    condition: mysql.enabled
  - name: postgresql
    version: 8.6.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 15.7.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: varnish
    version: 0.2.2
    repository: https://statcan.github.io/charts
    condition: varnish.enabled
