# When installing with Kind the cluster is required to have the following settings for the stateful assets to work
#
# For example:
# kind create cluster --config kind.yaml
#
# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
# - role: control-plane
#   # add a mount from /path/to/my/files on the host to /files on the node
#   extraMounts:
#   - hostPath: /tmp/drupal/shared/drupal-public
#     containerPath: /mnt/drupal/drupal-public
#   - hostPath: /tmp/drupal/shared/drupal-private
#     containerPath: /mnt/drupal/drupal-private

drupal:
  ## Drupal image version
  ## ref: https://hub.docker.com/drupalwxt/site-wxt/tags/
  ##
  image: drupalwxt/site-wxt
  tag: 4.0.0-rc3

  ## Site configuration
  ##
  profile: wxt
  siteEmail: admin@example.com
  siteName: Drupal Install Profile (WxT)

  ## User of the application
  ##
  username: admin

  ## Application password
  ##
  ## password: password

  # php-fpm healthcheck
  # Requires https://github.com/renatomefi/php-fpm-healthcheck in the container.
  # (note: official images do not contain this feature yet)
  healthcheck:
    enabled: true

  # Switch to canada.ca theme (only used if install and/or reconfigure are enabled)
  # Common options include: theme-wet-boew, theme-gcweb-legacy
  wxtTheme: theme-gcweb

  ## Extra settings.php settings
  ##
  extraSettings: ''
  #  |-
  #  $settings['trusted_host_patterns'] = ['^example\.com$'];

  ## Extra CLI scripts
  ##
  extraInstallScripts: ''
  #  |-
  #  drush config-set system.performance js.preprocess 0 -y;
  #  drush config-set system.performance css.preprocess 0 -y;

  # Install Drupal automatically
  install: true

  # Run migrations for default content
  migrate: true

  # Reconfigure on upgrade
  reconfigure: true

  # php-fpm healthcheck
  # Requires https://github.com/renatomefi/php-fpm-healthcheck in the container.
  # (note: official images do not contain this feature yet)
  healthcheck:
    enabled: true

  # Allows custom /var/www/html/sites/default/files and /private mounts
  disableDefaultFilesMount: true

  volumes:
    - name: files-public
      hostPath:
        path: /mnt/drupal/drupal-public
    - name: files-private
      hostPath:
        path: /mnt/drupal/drupal-private

  volumeMounts:
    - name: files-public
      mountPath: /var/www/html/sites/default/files
    - name: files-private
      mountPath: /private

nginx:
  image: drupalwxt/site-wxt
  tag: 4.0.0-rc3-nginx

  # Set your cluster's DNS resolution service here
  resolver: 10.0.0.10

  volumes:
    - name: files-public
      hostPath:
        path: /mnt/drupal/drupal-public

  volumeMounts:
    - name: files-public
      mountPath: /var/www/html/sites/default/files

redis:
  enabled: true

varnish:
  enabled: true

mysql:
  enabled: true
  mysqlPassword: testPassword

proxysql:
  enabled: true
  admin:
    user: proxysql
    password: proxysqlPassword
  monitor:
    user: monitor
    password: monitorPassword
  configuration:
    maxConnections: 2048
    serverVersion: "5.7.28"
    stackSize: 1048576

postgresql:
  enabled: false

pgbouncer:
  enabled: false
