drupal:
  ## Site configuration
  ##
  profile: wxt
  siteEmail: admin@example.com
  siteName: Drupal Install Profile (WxT)

  # Default WxT Library theme (only used if install and/or reconfigure are enabled)
  # Common options include: theme-wet-boew, theme-gcweb-legacy, theme-gcweb, ...
  wxtTheme: theme-gcweb

  # Install Drupal automatically
  install: true

  # Run migrations for default content
  migrate: true

  # Reconfigure on upgrade
  reconfigure: true

  # php-fpm healthcheck
  # Requires https://github.com/renatomefi/php-fpm-healthcheck in the container.
  # (note: official images do not contain this feature yet)
  healthcheck:
    enabled: true

nginx:
  # Set your cluster's DNS resolution service here
  resolver: 10.0.0.10

mysql:
  imageTag: 5.7.26

  mysqlPassword: SUPERsecureMYSQLpassword
  mysqlRootPassword: SUPERsecureMYSQLrootPASSWORD

  persistence:
    enabled: true

# Files: object storage
#
# Use Minio for object storage by default.
# You can use any S3 compatible object storage.
# Also:
#   - minio
#   - s3
#   - none
files:
  provider: minio

##
## MINIO
##
minio:
  enabled: true

  persistence:
    enabled: true

  defaultBucket:
    enabled: true

##
## AZURE EXAMPLE
##
# files:
#   cname:
#     enabled: true
#     hostname: wxt.blob.core.windows.net

# minio:
#   clusterDomain: cluster.cumulonimbus.zacharyseguin.ca
#   # Enable the Azure Gateway mode
#   azuregateway:
#     enabled: true

#   # Access Key should be set to the Azure Storage Account name
#   # Secret Key should be set to the Azure Storage Account access key
#   accessKey: STORAGE_ACCOUNT_NAME
#   secretKey: STORAGE_ACCOUNT_ACCESS_KEY

#   # Disable creation of default bucket.
#   # You should pre-create the bucket in Azure.
#   defaultBucket:
#     enabled: false
#     name: wxt

#   # We want a cluster ip assigned
#   service:
#     clusterIP: ''

#   # We don't need a persistent volume, since it's stored in Azure
#   persistence:
#     enabled: false
