apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drupal7.fullname" . }}-ssmtp
  labels:
    app.kubernetes.io/name: {{ include "drupal7.name" . }}
    helm.sh/chart: {{ include "drupal7.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ssmtp.conf: {{ tpl (.Files.Get "conf/ssmtp.conf") . | b64enc }}
