{{- if .Values.azureFile.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
{{- if .Values.azureFile.enabled }}
{{ toYaml .Values.azureFile.annotations | indent 4 }}
{{- end }}
  name: {{ include "drupal7.fullname" . }}-private
spec:
  accessModes:
    - {{ .Values.azureFile.accessMode }}
  resources:
    requests:
      storage: {{ .Values.azureFile.size }}
{{- if not .Values.azureFile.disableVolumeName }}
  volumeName: {{ include "drupal7.fullname" . }}-private
{{- end }}
{{- if or (eq "-" .Values.azureFile.storageClass) (.Values.azureFile.mountOptions) }}
  storageClassName: ""
{{- else if .Values.azureFile.storageClass }}
  storageClassName: "{{ .Values.azureFile.storageClass }}"
{{- end }}
{{- end }}
