{{- if .Values.sharedDisk.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
{{- if .Values.sharedDisk.enabled }}
{{ toYaml .Values.sharedDisk.annotations | indent 4 }}
{{- end }}
  name: {{ include "drupal7.fullname" . }}-private
spec:
  accessModes:
    - {{ .Values.sharedDisk.accessMode }}
  resources:
    requests:
      storage: {{ .Values.sharedDisk.size }}
{{- if not .Values.sharedDisk.disableVolumeName }}
  volumeName: {{ include "drupal7.fullname" . }}-private
{{- end }}
{{- if eq "-" .Values.sharedDisk.storageClass }}
  storageClassName: ""
{{- else if .Values.sharedDisk.storageClass }}
  storageClassName: "{{ .Values.sharedDisk.storageClass }}"
{{- end }}
{{- end }}
