apiVersion: v1
kind: Service
metadata:
  name: {{ include "drupal7.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drupal7.name" . }}
    helm.sh/chart: {{ include "drupal7.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: tcp-php-fpm
      port: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "drupal7.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    tier: drupal7
  type:  {{ .Values.drupal.serviceType }}
