{{- if .Values.drupal.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drupal.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
automountServiceAccountToken: {{ .Values.drupal.serviceAccount.automountServiceAccountToken }}
{{- end }}
