{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
{{ include "varnish.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.admin.secret }}
  secret: {{ .Values.admin.secret | b64enc }}
  {{- else }}
  secret: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
{{- end }}
