apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drupal.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
    {{- if .Values.nginx.configuration }}
    {{- tpl .Values.nginx.configuration . | nindent 4 }}
    {{- else }}
    {{- tpl (.Files.Get "conf/nginx.conf") . | nindent 4 }}
    {{- end }}
