apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drupal7.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drupal7.name" . }}
    helm.sh/chart: {{ include "drupal7.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  php.ini: |
{{ tpl (.Files.Get "conf/php.ini") . | indent 4 }}
  opcache-recommended.ini: |
{{ tpl (.Files.Get "conf/opcache-recommended.ini") . | indent 4 }}
  www.conf: |
{{ tpl (.Files.Get "conf/www.conf") . | indent 4 }}
  settings.php: |
{{- if eq "d7" .Values.drupal.version }}
{{ tpl (.Files.Get "conf/settings.d7.php") . | indent 4 }}
{{- else }}
  settings.php:
    <?php

    // Unknown drupal version specified.
{{- end }}

{{- if .Values.drupal.extraSettings }}
  extra.settings.php: |
    <?php

    {{ .Values.drupal.extraSettings | nindent 4}}
{{- end }}
