apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drupal7.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "drupal7.name" . }}
    helm.sh/chart: {{ include "drupal7.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
{{ tpl (.Files.Get "conf/nginx.conf") . | indent 4 }}
