{{- if .Values.azureFile.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
{{- if .Values.azureFile.annotations }}
  annotations:
{{ toYaml .Values.azureFile.annotations | indent 4 }}
{{- end }}
  name: {{ include "drupal.fullname" . }}-private
spec:
  capacity:
    storage: {{ .Values.azureFile.size }}
  accessModes:
    - {{ .Values.azureFile.accessMode }}
{{- if eq "-" .Values.azureFile.storageClass }}
  storageClassName: ""
{{- else if .Values.azureFile.storageClass }}
  storageClassName: "{{ .Values.azureFile.storageClass }}"
{{- end }}
{{- if .Values.azureFile.private }}
{{ toYaml .Values.azureFile.private | indent 2 }}
{{- end }}
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=82
    - gid=82
    - mfsymlinks
    - nobrl
    - cache=none
{{- end }}
