{{- if .Values.azureFile.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
{{- if .Values.azureFile.annotations }}
  annotations:
{{ toYaml .Values.azureFile.annotations | indent 4 }}
{{- end }}
  name: {{ include "drupal.fullname" . }}-public
spec:
  capacity:
    storage: {{ .Values.azureFile.size }}
  accessModes:
    - {{ .Values.azureFile.accessMode }}
{{- if eq "-" .Values.azureFile.storageClass }}
  storageClassName: ""
{{- else if .Values.azureFile.storageClass }}
  storageClassName: "{{ .Values.azureFile.storageClass }}"
{{- end }}
{{- if .Values.azureFile.public }}
{{ toYaml .Values.azureFile.public | indent 2 }}
{{- end }}
{{- if .Values.azureFile.mount }}
  mountOptions:
{{ toYaml .Values.azureFile.mount | indent 4 }}
{{- end }}
{{- end }}
