apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
{{ include "varnish.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "varnish.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "varnish.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap/varnish.yaml") . | sha256sum }}
{{- if .Values.admin.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret/varnish.yaml") . | sha256sum }}
{{- end }}
    spec:
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.varnishd.image }}:{{ default .Chart.AppVersion .Values.varnishd.tag }}"
          imagePullPolicy: {{ .Values.varnishd.pullPolicy }}
          command:
          - varnishd
          - -F
          - -f
          - /etc/varnish/default.vcl
          - -a
          - http=:{{ .Values.service.port }},HTTP
{{- if .Values.admin.enabled }}
          - -T
          - 0.0.0.0:{{ .Values.admin.port }}
          - -S
          - /etc/varnish/secret
{{- end }}
          - -p
          - feature=+http2
          - -s
          - malloc,{{ .Values.memorySize }}
          - -n
          - /tmp/varnish_workdir
          volumeMounts:
            - name: varnish-config
              mountPath: /etc/varnish/default.vcl
              subPath: default.vcl
{{- if .Values.admin.enabled }}
            - name: varnish-secret
              mountPath: /etc/varnish/secret
              subPath: secret
{{- end }}
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
{{- if .Values.admin.enabled }}
            - name: tcp-admin
              containerPort: {{ .Values.admin.port }}
              protocol: TCP
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.varnishd.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: varnish-config
        configMap:
          name: "{{ include "varnish.fullname" . }}"
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 6 }}
{{- end }}
{{- if .Values.admin.enabled }}
      - name: varnish-secret
        secret:
          secretName: {{ include "varnish.fullname" . }}
{{- end }}
