apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drupal.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "drupal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "drupal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: frontend
        {{- if .Values.nginx.podLabels }}
        {{- toYaml .Values.nginx.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.nginx.podAnnotations }}
        {{- toYaml .Values.nginx.podAnnotations | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/cm/nginx.yaml") . | sha256sum }}
    spec:
      {{- if .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml .Values.nginx.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nginx.nodeSelector | nindent 8 }}
      {{- end }}
      initContainers:
      {{- if not (eq .Values.drupal.siteRoot "/") }}
        - name: init-site-root
          image: 'alpine:3.10'
          command:
            - /bin/sh
            - '-c'
            - |
              mkdir -p "/webroot$(dirname "{{ .Values.drupal.siteRoot }}")"
              ln -s /var/www/html "/webroot{{ .Values.drupal.siteRoot }}"
          volumeMounts:
            - name: webroot
              mountPath: /webroot
      {{- end }}
      containers:
      - image: "{{ .Values.nginx.image }}:{{ default (print .Chart.AppVersion "-nginx") .Values.nginx.tag }}"
        imagePullPolicy: {{ default "" .Values.nginx.imagePullPolicy | quote }}
        name: nginx
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        {{- if .Values.nginx.healthcheck.enabled }}
        {{- if .Values.nginx.healthcheck.probes }}
        {{- toYaml .Values.nginx.healthcheck.probes | nindent 8 }}
        {{- else }}
        readinessProbe:
          httpGet:
            path: /_healthz
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /_healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 5
        {{- end }}
        {{- end }}
        {{- if .Values.nginx.resources }}
        resources:
          {{- toYaml .Values.nginx.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: cm-nginx
          readOnly: true
          subPath: nginx.conf
        {{- if not .Values.drupal.disableDefaultFilesMount }}
        - name: files
          mountPath: /var/www/html/sites/default/files
          subPath: public
        {{- end }}
        {{- if not (eq .Values.drupal.siteRoot "/") }}
        - name: webroot
          mountPath: /webroot
        {{- end }}
        {{- if .Values.nginx.volumeMounts }}
        {{- toYaml .Values.nginx.volumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.nginx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.nginx.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.nginx.securityContext }}
      securityContext:
        fsGroup: {{ .Values.nginx.securityContext.fsGroup }}
      {{- end }}
      volumes:
      - name: cm-nginx
        configMap:
          name: {{ include "drupal.fullname" . }}-nginx
      {{- if .Values.drupal.persistence.enabled }}
      - name: files
        persistentVolumeClaim:
          claimName: {{ template "drupal.fullname" . }}-drupal
      {{- else if or (.Values.azure.azureFile.enabled) (.Values.azure.sharedDisk.enabled) }}
      - name: files-public
        persistentVolumeClaim:
          claimName: {{ include "drupal.fullname" . }}-public
      {{- else if not .Values.drupal.disableDefaultFilesMount }}
      - name: files
        emptyDir: {}
      {{- end }}
      {{- if not (eq .Values.drupal.siteRoot "/") }}
      - name: webroot
        emptyDir: {}
      {{- end }}
      {{- if .Values.nginx.volumes }}
      {{- toYaml .Values.nginx.volumes | nindent 6 }}
      {{- end }}
