{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "varnish.fullname" . }}-admin
  labels:
{{ include "varnish.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-admin
      port: {{ .Values.admin.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "varnish.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
