apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "varnish.fullname" . }}"
  labels:
{{ include "varnish.labels" . | indent 4 }}
data:
{{- if .Values.varnishConfigContent }}
  default.vcl: |
{{ tpl .Values.varnishConfigContent . | indent 4 }}
{{- else }}
  default.vcl: |
    vcl 4.0;

    # Varnish configuration was not provided to the helm chart.
    # Please provide `varnishConfigContent`

    backend placeholder {
      .host = "localhost";
      .port = "80";
    }

    sub vcl_recv {
      return (synth(700, "Service Unavailable"));
    }

    sub vcl_synth {
      set resp.status = 503;
      return (deliver);
    }

{{- end }}
