name: drupal7
apiVersion: v2
type: application
version: 0.1.17
appVersion: "4.54"
description: Drupal 7 variant of the Web Experience Toolkit (WetKit).
keywords:
- drupal
- cms
- wetkit
- http
- web
- application
- php
home: http://www.drupal.org/project/wetkit
icon: https://bitnami.com/assets/stacks/drupal/img/drupal-stack-220x234.png
sources:
- https://github.com/wet-boew/wet-boew-drupal
maintainers:
- name: sylus
  email: william.hearn@canada.ca
- name: zachomedia
  email: zachary.seguin@canada.ca
engine: gotpl
dependencies:
  - name: mysql
    version: 1.6.2
    repository: https://charts.helm.sh/stable
    condition: mysql.enabled
  - name: postgresql
    version: 8.6.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 12.10.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: varnish
    version: 0.2.0
    repository: https://statcan.github.io/charts
    condition: varnish.enabled
