{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
{{- $fullName := include "drupal.fullname" . -}}
{{- $releaseName := .Release.Name -}}
{{- $varnishEnabled := .Values.varnish.enabled -}}
{{- range $index, $route := .Values.routes }}
{{- if $route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $route.name | default (printf "%s-%d" $fullName $index) }}
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" $ }}
    helm.sh/chart: {{ include "drupal.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ first $route.hosts | quote }}
  {{- with $route.path }}
  path: {{ . | quote }}
  {{- end }}
  to:
    kind: Service
    {{- if $varnishEnabled }}
    name: {{ $releaseName }}-varnish
    {{- else }}
    name: {{ $fullName }}-nginx
    {{- end }}
  port:
    targetPort: 8080
  {{- with $route.tls }}
  tls:
    termination: {{ .termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .insecureEdgeTerminationPolicy | default "Redirect" }}
    {{- if .externalCertificate }}
    externalCertificate:
      name: {{ .externalCertificate.name | quote }}
    {{- else }}
    {{- if .key }}
    key: |-{{ .key | nindent 6 }}
    {{- end }}
    {{- if .certificate }}
    certificate: |-{{ .certificate | nindent 6 }}
    {{- end }}
    {{- if .caCertificate }}
    caCertificate: |-{{ .caCertificate | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
