{{- if .Values.azure.azureFile.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
{{- if .Values.azure.azureFile.enabled }}
{{ toYaml .Values.azure.azureFile.annotations | indent 4 }}
{{- end }}
  name: {{ include "drupal.fullname" . }}-private
spec:
  accessModes:
    - {{ .Values.azure.azureFile.accessMode }}
  resources:
    requests:
      storage: {{ .Values.azure.azureFile.size }}
{{- if not .Values.azure.azureFile.disableVolumeName }}
  volumeName: {{ include "drupal.fullname" . }}-private
{{- end }}
{{- if .Values.azure.storageClass.create }}
  storageClassName: {{ include "drupal.fullname" . }}-csi-azure
{{- else if eq "-" .Values.azure.azureFile.storageClass }}
  storageClassName: ""
{{- else if .Values.azure.azureFile.storageClass }}
  storageClassName: "{{ .Values.azure.azureFile.storageClass }}"
{{- end }}
{{- end }}
