{{- if .Values.nginx.podDisruptionBudget.enabled }}

{{- $name := include "drupal.name" . -}}
{{- $fullName := include "drupal.fullname" . -}}-nginx
{{- $chartName := include "drupal.chart" . -}}
{{- $release := .Release }}
{{- $values := .Values }}

---
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chartName }}
    app.kubernetes.io/instance: {{ $release.Name }}
    app.kubernetes.io/managed-by: {{ $release.Service }}

spec:
  {{- with $values.nginx.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}

  {{- with $values.nginx.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ $release.Name }}

{{- end }}
