apiVersion: v1
kind: Service
metadata:
  name: {{ include "drupal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: tcp-php-fpm
      port: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    tier: drupal
  type: {{ .Values.drupal.serviceType }}
