apiVersion: v1
kind: Service
metadata:
  name: {{ include "drupal.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    tier: frontend
  type:  {{ .Values.nginx.serviceType }}
