apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drupal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.drupal.username }}
  username: {{ default "" .Values.drupal.username | b64enc | quote }}
  {{ else }}
  username: {{ "admin" | b64enc | quote }}
  {{ end }}
  {{ if .Values.drupal.password }}
  password: {{ default "" .Values.drupal.password | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.external.enabled }}
  databasePassword: {{ .Values.external.password | b64enc | quote }}
  {{ end }}
