{{- if .Values.proxysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drupal.fullname" . }}-proxysql
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  proxysql.conf: {{ tpl (.Files.Get "conf/proxysql.conf") . | b64enc }}
{{- end }}
