{{- if and (not .Values.drupal.usePasswordFiles) (not .Values.drupal.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drupal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{ default "admin" .Values.drupal.username | b64enc | quote }}
  password: {{ default (randAlphaNum 10) .Values.drupal.password | b64enc | quote }}
  {{- if .Values.external.enabled }}
  databasePassword: {{ .Values.external.password | b64enc | quote }}
  {{- end }}
{{- end }}
