{{- if not .Values.drupal.usePasswordFiles }}
{{- $name := include "drupal.fullname" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{ if and $existing (hasKey $existing.data "username") }}{{ index $existing.data "username" | quote }}{{ else if .Values.drupal.username }}{{ .Values.drupal.username | b64enc | quote }}{{ else }}{{ "admin" | b64enc | quote }}{{ end }}
  password: {{ if and $existing (hasKey $existing.data "password") }}{{ index $existing.data "password" | quote }}{{ else if .Values.drupal.password }}{{ .Values.drupal.password | b64enc | quote }}{{ else }}{{ randAlphaNum 10 | b64enc | quote }}{{ end }}
  {{- if .Values.external.enabled }}
  databasePassword: {{ if and $existing (hasKey $existing.data "databasePassword") }}{{ index $existing.data "databasePassword" | quote }}{{ else }}{{ .Values.external.password | b64enc | quote }}{{ end }}
  {{- end }}
{{- end }}
