{{- if .Values.azureFile.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
{{- if .Values.azureFile.annotations }}
  annotations:
{{ toYaml .Values.azureFile.annotations | indent 4 }}
{{- end }}
  name: {{ include "drupal7.fullname" . }}-private
spec:
  capacity:
    storage: {{ .Values.azureFile.size }}
  accessModes:
    - {{ .Values.azureFile.accessMode }}
{{- if .Values.azureFile.private }}
{{ toYaml .Values.azureFile.private | indent 2 }}
{{- end }}
{{- if .Values.azureFile.mountOptions }}
  mountOptions:
{{ toYaml .Values.azureFile.mountOptions | indent 4 }}
{{- end }}
{{- end }}
