kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /tmp/drupal/shared/drupal-public
    containerPath: /mnt/drupal/drupal-public
  - hostPath: /tmp/drupal/shared/drupal-private
    containerPath: /mnt/drupal/drupal-private
