## Configure Ingress resource that allow you to access the Solr installation
## Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  enabled: false
  # className: nginx
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  path: /.*
  pathType: ImplementationSpecific
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

solr:
  # https://github.com/apache/solr-operator/blob/main/docs/solr-cloud/solr-cloud-crd.md#k8s-oper-user
  basicAuthSecret:
  replicas: 1
  solrJavaMem: "-Xms1g -Xmx5g"
  # customSolrKubeOptions:
  #   podOptions:
  #     livenessProbe:
  #       periodSeconds: 15
  #       timeoutSeconds: 5
  #     readinessProbe:
  #       timeoutSeconds: 5
  #     resources:
  #       limits:
  #         memory: "5Gi"
  #       requests:
  #         cpu: "250m"
  #         memory: "256Mi"

  storage:
    size: 5Gi

zookeeper:
  replicas: 1
  resources: {}
    # limits:
    #   memory: 2Gi
    # requests:
    #   cpu: 250m
    #   memory: 256Mi

  storage:
    size: 5Gi

## Configure Istio
## ref: http://istio.io
##
destinationRule:
  enabled: false
  mode: DISABLE
