## Configure Ingress resource that allow you to access the Solr installation
## Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  enabled: false
  # className: nginx
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  path: /.*
  pathType: ImplementationSpecific
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

solr:
  # https://github.com/apache/solr-operator/blob/main/docs/solr-cloud/solr-cloud-crd.md#k8s-oper-user
  basicAuthSecret:
  solrJavaMem: "-Xms1g -Xmx5g"
  resources: {}
    # requests:
    #   memory: "256Mi"
    #   cpu: "100m"
    # limits:
    #   memory: "1Gi"
    #   cpu: "500m"
  storage:
    size: 5Gi

zookeeper:
  resources: {}
    # requests:
    #   memory: "256Mi"
    #   cpu: "100m"
    # limits:
    #   memory: "1Gi"
    #   cpu: "500m"
  storage:
    size: 5Gi

## Configure Istio
## ref: http://istio.io
##
destinationRule:
  enabled: false
  mode: DISABLE

## Solr
## Ref: https://github.com/drupalwxt/helm-drupal/tree/master/solr
replicas: 1
